language: csharp
solution: WebApplication1.sln

addons:
  sonarcloud:
    organization: "ponnukumar"
    token:
      secure: "1b94910ffe367b779a28ea1590578a25a4afd7ff"
      
script:
  - sonar-scanner
  
cache:
  directories:
    - '$HOME/.sonar/cache'
