language: csharp
solution: WebApplication1.sln

addons:
  sonarcloud:
    organization: "CodeAnalysis"
    token:
      secure: "1b94910ffe367b779a28ea1590578a25a4afd7ff"

cache:
  directories:
    - '$HOME/.sonar/cache'
