language: csharp
solution: WebApplication1.sln
mono:
  - latest 

addons:
  sonarcloud:
    organization: "ponnukumar-github"
    token:
      secure: "1b94910ffe367b779a28ea1590578a25a4afd7ff"
      
script:
  - xbuild /p:Configuration=Release WebApplication1.sln
  - sonar-scanner
   
  
install:
  - nuget restore WebApplication1.sln
  
cache:
  directories:
    - '$HOME/.sonar/cache'
